// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:65343580-3e0a-4439-886c-055c993c16cb",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_NVG5wBw0n",
    "aws_user_pools_web_client_id": "5rni0uclcrf39a9olk75dh4aat",
    "oauth": {}
};


export default awsmobile;
